Valor = input('Digite algo: ')
print('O tipo dessa primitava é: ', type(Valor))
print('Só tem espaço? ', Valor.isspace())
print('É um numero? ', Valor.isnumeric())
print('É alfabético? ', Valor.isalpha())
print('É alfanumérico? ', Valor.isalnum())
print('Está em minuscula? ', Valor.islower())
print('Está em maiuscula? ', Valor.isupper())
print('Está captalizada? ', Valor.istitle())
